//! A fake SPICE server that replays a canned audio session.
//!
//! It exists so the console's WebSocket proxy can be tested against something
//! that speaks the real link handshake and the real mini-header framing
//! without starting QEMU, and so the golden vectors the TypeScript codec
//! consumes come from the same code path the Rust probe uses.

use std::path::Path;
use std::sync::Arc;

use rsa::pkcs8::EncodePublicKey;
use rsa::{Oaep, RsaPrivateKey, RsaPublicKey};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{UnixListener, UnixStream};

use crate::error::SpiceError;
use crate::link::{LinkHeader, LinkMess, LinkReply, cap_word};
use crate::message::{
    AudioData, Framer, MainInit, Message, ModeMessage, PlaybackStart, RecordStart,
};
use crate::protocol::{self, AudioMode, ChannelType};

/// The connection id this fake server hands out in `MSG_MAIN_INIT`.
pub const FAKE_CONNECTION_ID: u32 = 0x5069_4345;
/// Sample rate of the canned playback tone.
pub const FAKE_FREQUENCY: u32 = 48_000;
/// Channel count of the canned playback tone.
pub const FAKE_CHANNELS: u32 = 2;
/// Frames of canned playback the server sends before stopping.
pub const FAKE_PLAYBACK_FRAMES: u32 = 10;
/// Samples per canned playback frame, per channel.
pub const FAKE_FRAME_SAMPLES: u32 = 480;

/// Link error: the requested channel is not available on this server.
pub const LINK_ERR_CHANNEL_NOT_AVAILABLE: u32 = 9;
/// Link error: the connection id does not belong to a live session.
pub const LINK_ERR_BAD_CONNECTION_ID: u32 = 8;

/// A fake server bound to a Unix socket.
#[derive(Debug)]
pub struct FakeServer {
    listener: UnixListener,
    key: Arc<RsaPrivateKey>,
    pub_key: Arc<Vec<u8>>,
}

/// One 480-sample stereo S16 frame of a 440 Hz tone, deterministic in `index`.
///
/// The probe and the fixture generator share this so a golden vector can be
/// regenerated byte for byte.
#[must_use]
pub fn tone_frame(index: u32) -> Vec<u8> {
    let mut out = Vec::with_capacity((FAKE_FRAME_SAMPLES * FAKE_CHANNELS * 2) as usize);
    for sample in 0..FAKE_FRAME_SAMPLES {
        let position = index * FAKE_FRAME_SAMPLES + sample;
        let phase = f64::from(position) * 440.0 * std::f64::consts::TAU / f64::from(FAKE_FREQUENCY);
        #[allow(clippy::cast_possible_truncation)]
        let value = (phase.sin() * 8000.0) as i16;
        out.extend_from_slice(&value.to_le_bytes());
        out.extend_from_slice(&value.to_le_bytes());
    }
    out
}

impl FakeServer {
    /// Bind a fake server, generating the RSA key the ticket step needs.
    ///
    /// # Errors
    /// Returns [`SpiceError`] when the socket cannot be bound or a key cannot
    /// be generated.
    pub fn bind(socket: &Path) -> Result<Self, SpiceError> {
        let listener = UnixListener::bind(socket)
            .map_err(|_| SpiceError::Malformed("fake SPICE socket could not be bound"))?;
        let key = RsaPrivateKey::new(&mut rsa::rand_core::OsRng, 1024)
            .map_err(|_| SpiceError::Malformed("RSA key generation failed"))?;
        let pub_key = RsaPublicKey::from(&key)
            .to_public_key_der()
            .map_err(|_| SpiceError::Malformed("RSA key could not be encoded"))?
            .as_bytes()
            .to_vec();
        Ok(Self {
            listener,
            key: Arc::new(key),
            pub_key: Arc::new(pub_key),
        })
    }

    /// Serve connections until the process is stopped.
    ///
    /// # Errors
    /// Returns [`SpiceError`] only when the listener itself fails; a single
    /// misbehaving connection is closed and logged, not fatal.
    pub async fn serve(&self) -> Result<(), SpiceError> {
        loop {
            let Ok((stream, _)) = self.listener.accept().await else {
                return Err(SpiceError::Malformed("fake SPICE listener failed"));
            };
            let key = Arc::clone(&self.key);
            let pub_key = Arc::clone(&self.pub_key);
            tokio::spawn(async move {
                if let Err(error) = connection(stream, &key, &pub_key).await {
                    eprintln!("fake spice connection closed: {error}");
                }
            });
        }
    }
}

async fn read_exact(stream: &mut UnixStream, len: usize) -> Result<Vec<u8>, SpiceError> {
    let mut buffer = vec![0u8; len];
    stream
        .read_exact(&mut buffer)
        .await
        .map_err(|_| SpiceError::Short)?;
    Ok(buffer)
}

async fn refuse(stream: &mut UnixStream, error: u32) -> Result<(), SpiceError> {
    let reply = LinkReply {
        error,
        pub_key: vec![0; protocol::TICKET_PUBKEY_BYTES],
        common_caps: Vec::new(),
        channel_caps: Vec::new(),
    }
    .encode();
    stream
        .write_all(&LinkHeader::encode(u32::try_from(reply.len()).unwrap()))
        .await
        .map_err(|_| SpiceError::Short)?;
    stream
        .write_all(&reply)
        .await
        .map_err(|_| SpiceError::Short)
}

async fn connection(
    mut stream: UnixStream,
    key: &RsaPrivateKey,
    pub_key: &[u8],
) -> Result<(), SpiceError> {
    let head = LinkHeader::parse(&read_exact(&mut stream, protocol::LINK_HEADER_BYTES).await?)?;
    let mess = LinkMess::parse(&read_exact(&mut stream, head.size as usize).await?)?;
    let Some(kind) = mess.channel() else {
        refuse(&mut stream, LINK_ERR_CHANNEL_NOT_AVAILABLE).await?;
        return Err(SpiceError::UnsupportedChannel(mess.channel_type));
    };
    let expected = if kind == ChannelType::Main {
        0
    } else {
        FAKE_CONNECTION_ID
    };
    if mess.connection_id != expected {
        refuse(&mut stream, LINK_ERR_BAD_CONNECTION_ID).await?;
        return Err(SpiceError::LinkRejected(LINK_ERR_BAD_CONNECTION_ID));
    }
    let opus = match kind {
        ChannelType::Playback => mess.has_channel_cap(protocol::PLAYBACK_CAP_OPUS),
        ChannelType::Record => mess.has_channel_cap(protocol::RECORD_CAP_OPUS),
        ChannelType::Main => false,
    };
    let reply = LinkReply {
        error: protocol::LINK_ERR_OK,
        pub_key: pub_key.to_vec(),
        // The fake server always offers mini headers and SPICE tickets; it
        // never offers SASL, which this codec would refuse anyway.
        common_caps: vec![
            cap_word(protocol::COMMON_CAP_PROTOCOL_AUTH_SELECTION)
                | cap_word(protocol::COMMON_CAP_AUTH_SPICE)
                | cap_word(protocol::COMMON_CAP_MINI_HEADER),
        ],
        // Opus is only echoed back when the client offered it, so a raw-only
        // client keeps a raw stream.
        channel_caps: if opus {
            vec![cap_word(match kind {
                ChannelType::Record => protocol::RECORD_CAP_OPUS,
                _ => protocol::PLAYBACK_CAP_OPUS,
            })]
        } else {
            Vec::new()
        },
    }
    .encode();
    stream
        .write_all(&LinkHeader::encode(u32::try_from(reply.len()).unwrap()))
        .await
        .map_err(|_| SpiceError::Short)?;
    stream
        .write_all(&reply)
        .await
        .map_err(|_| SpiceError::Short)?;

    let selection = read_exact(&mut stream, 4).await?;
    if u32::from_le_bytes(selection[..4].try_into().unwrap()) != protocol::AUTH_SELECTION_SPICE {
        return Err(SpiceError::Malformed(
            "fake server only offers SPICE tickets",
        ));
    }
    let ticket = read_exact(&mut stream, protocol::TICKET_BYTES).await?;
    // Any password is accepted, matching `disable-ticketing=on`, but the blob
    // must still decrypt: a client that skips the ticket is a protocol error.
    key.decrypt(Oaep::new::<sha1::Sha1>(), &ticket)
        .map_err(|_| SpiceError::Malformed("ticket did not decrypt"))?;
    stream
        .write_all(&protocol::LINK_ERR_OK.to_le_bytes())
        .await
        .map_err(|_| SpiceError::Short)?;

    match kind {
        ChannelType::Main => main_channel(stream).await,
        ChannelType::Playback => playback_channel(stream).await,
        ChannelType::Record => record_channel(stream).await,
    }
}

async fn write_message(stream: &mut UnixStream, message: &Message) -> Result<(), SpiceError> {
    stream
        .write_all(&message.encode())
        .await
        .map_err(|_| SpiceError::Short)
}

async fn main_channel(mut stream: UnixStream) -> Result<(), SpiceError> {
    write_message(
        &mut stream,
        &Message {
            kind: protocol::MSG_MAIN_INIT,
            payload: MainInit {
                connection_id: FAKE_CONNECTION_ID,
                multi_media_time: 0,
            }
            .encode(),
        },
    )
    .await?;
    // Hold the channel open: the proxy binds its child links to a live main,
    // so the fake server must behave the same way.
    let mut sink = [0u8; 4096];
    while stream.read(&mut sink).await.unwrap_or(0) > 0 {}
    Ok(())
}

async fn playback_channel(mut stream: UnixStream) -> Result<(), SpiceError> {
    write_message(
        &mut stream,
        &Message {
            kind: protocol::MSG_PLAYBACK_MODE,
            payload: ModeMessage {
                time: 0,
                // The canned stream is raw even when Opus was negotiated: no
                // encoder is linked here, and a raw stream is what the
                // TypeScript fixtures assert against.
                mode: AudioMode::Raw,
                data: Vec::new(),
            }
            .encode(),
        },
    )
    .await?;
    write_message(
        &mut stream,
        &Message {
            kind: protocol::MSG_PLAYBACK_START,
            payload: PlaybackStart {
                channels: FAKE_CHANNELS,
                format: protocol::AUDIO_FMT_S16,
                frequency: FAKE_FREQUENCY,
                time: 0,
            }
            .encode(),
        },
    )
    .await?;
    for index in 0..FAKE_PLAYBACK_FRAMES {
        write_message(
            &mut stream,
            &Message {
                kind: protocol::MSG_PLAYBACK_DATA,
                payload: AudioData {
                    time: index * 10,
                    samples: tone_frame(index),
                }
                .encode(),
            },
        )
        .await?;
    }
    write_message(
        &mut stream,
        &Message {
            kind: protocol::MSG_PLAYBACK_STOP,
            payload: Vec::new(),
        },
    )
    .await?;
    let mut sink = [0u8; 4096];
    while stream.read(&mut sink).await.unwrap_or(0) > 0 {}
    Ok(())
}

async fn record_channel(mut stream: UnixStream) -> Result<(), SpiceError> {
    write_message(
        &mut stream,
        &Message {
            kind: protocol::MSG_RECORD_START,
            payload: RecordStart {
                channels: FAKE_CHANNELS,
                format: protocol::AUDIO_FMT_S16,
                frequency: FAKE_FREQUENCY,
            }
            .encode(),
        },
    )
    .await?;
    let mut framer = Framer::new();
    let mut chunk = [0u8; 16 * 1024];
    let mut frames = 0u32;
    loop {
        let read = stream
            .read(&mut chunk)
            .await
            .map_err(|_| SpiceError::Short)?;
        if read == 0 {
            break;
        }
        for message in framer.feed(&chunk[..read])? {
            match message.kind {
                protocol::MSGC_RECORD_MODE => {
                    ModeMessage::parse(&message.payload)?;
                }
                protocol::MSGC_RECORD_START_MARK => {
                    if message.payload.len() < 4 {
                        return Err(SpiceError::Short);
                    }
                }
                protocol::MSGC_RECORD_DATA => {
                    AudioData::parse(&message.payload)?;
                    frames += 1;
                }
                _ => return Err(SpiceError::Malformed("unexpected client record message")),
            }
        }
    }
    eprintln!("fake spice record channel received {frames} data messages");
    Ok(())
}
