PACKAGE_NAME="unifi-qemu-analysis-kvm"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="kvm_analysis_guard"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="no"
MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make KDIR=${kernel_source_dir} clean"
